FROM docker.io/golang:1-alpine

WORKDIR "/go/src"

ADD go.mod /go/src/go.mod
ADD go.sum /go/src/go.sum
ADD vendor /go/src/vendor
ADD pkg /go/src/pkg
ADD data-plane/symbols.txt /go/src/data-plane/symbols.txt
ADD data-plane/main.go /go/src/data-plane/main.go

ENV GOOS=linux
ENV GOARCH=arm64
RUN go build -o /go/bin/data-plane data-plane/main.go
ENTRYPOINT /go/bin/data-plane
