apiVersion: v1
kind: Service
metadata:
  name: gossip-srv
spec:
  selector:
    app: gossip
  clusterIP: None
  ports:
    - protocol: TCP
      name: memberlist
      port: 7946
      targetPort: 7946
